DROP TABLE IF EXISTS Kayttaja CASCADE; -- Muista IF EXISTS ja CASCADE parametrit!
DROP TABLE IF EXISTS Tapahtuma CASCADE;
DROP TABLE IF EXISTS Liitostaulu CASCADE;
DROP TABLE IF EXISTS Ryhma CASCADE;
DROP TABLE IF EXISTS Perustaja CASCADE;